template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.4.0/EC2/jc-ec2-linux.j2
stack_name: jc-ec2-linux
dependencies:
  - prod/bootstrap.yaml
parameters:
  JcUserId: dwayne.jeng@sagebase.org
  KeyName: bridge-ops
  InstanceType: t3a.micro
  JcConnectKey: !ssm /infra/JcConnectKey-djeng
  JcServiceApiKey:
  JcSystemsGroupId:
  VpcName: BridgeServer2-vpc
  AMIId: sagebio-base-aws-linux2-LATEST
  VolumeSize: 10
