template:
  type: http
  url: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/EC2/basic-ec2.j2
stack_name: bridge-ops
dependencies:
  - prod/bootstrap.yaml
parameters:
  InstanceType: t3a.micro
  VpcId: vpc-0818659c21d92f2a3
  SubnetId: subnet-0226fb44adc9329c8
